name: polyline_animation_v1
description: A new Flutter package project.
version: 0.0.1
author: Michael Valdiviezo
homepage: polyline_animation

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
